name = "nova-preview"
compatibility_date = "2026-06-21"
pages_build_output_dir = "."

[vars]
PUBLIC_ORIGIN = "https://dev.nova-7.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "nova-db"
database_id = "f440489c-aa57-4da2-bf5c-742fad98fc18"

[[durable_objects.bindings]]
name = "VOICE_ROOMS"
class_name = "VoiceRoom"
script_name = "nova-voice-rooms"
