const fs = require('fs');
const assert = require('assert');
const api = fs.readFileSync('website/js/nova-v7-api.js','utf8');
const social = fs.readFileSync('website/js/social.js','utf8');
const worker = fs.readFileSync('_worker.js','utf8');
const uno = fs.readFileSync('website/js/nova-uno.js','utf8');
const vc = fs.readFileSync('website/js/nova-social-vc.js','utf8');
assert(api.includes('nova:shared-read:v1:'), 'cross-tab read cache missing');
assert(api.includes('inFlightReads = new Map()'), 'same-tab request coalescing missing');
assert(api.includes('return 5500;'), 'message shared TTL missing');
assert(api.includes('return 20000;'), 'social shared TTL missing');
assert(api.includes('if (!document.hidden) syncPresence()'), 'hidden-tab presence throttling missing');
assert(social.includes('CHAT_BASE_MS=6500, CHAT_MAX_MS=30000'), 'chat backoff reduction missing');
assert(social.includes('_reactionPollTimer=setInterval(_pollReactions,7000)'), 'reaction polling reduction missing');
assert(social.includes('_typingPollTimer=setInterval(pollTyping,5000)'), 'typing polling reduction missing');
assert(social.includes('if(a.reactionsIncluded!==false)applyReactionSnapshot'), 'incremental reaction guard missing');
assert(worker.includes('const includeReactions = !after;'), 'backend incremental reaction aggregation reduction missing');
assert(worker.includes('reactionsIncluded: includeReactions'), 'backend reaction marker missing');
assert(uno.includes('setTimeout(poll,15000)'), 'hidden UNO throttling missing');
assert(uno.includes('setTimeout(poll,1500)'), 'active UNO polling reduction missing');
assert(vc.includes('!document.hidden)refreshRooms()},20000'), 'voice room hidden-tab throttling missing');
console.log('db-reduction-regression: PASS');
