const fs = require('fs');
const assert = require('assert');
const sj = fs.readFileSync('proxy/scramjet/scramjet.js','utf8');
const sw = fs.readFileSync('proxy/sw.js','utf8');
const mgr = fs.readFileSync('proxy/js/nova-proxy-manager.js','utf8');
assert(sj.includes('t.attribs.integrity="",delete t.attribs["scramjet-attr-integrity"]') || sj.includes('delete t.attribs.integrity,delete t.attribs["scramjet-attr-integrity"]'), 'Scramjet HTML rewriter must neutralize SRI without a recoverable marker');
assert(!sj.includes('t.attribs[\"scramjet-attr-integrity\"]=e'), 'Scramjet must not preserve stale integrity hashes in rewritten HTML');
assert(sw.includes('scramjet-attr-integrity') && sw.includes('integrity\\s*='), 'SW must neutralize both SRI forms');
assert(mgr.includes('async function bufferFontResponseExactly'), 'font exact-buffer boundary missing');
assert(mgr.includes('response = await bufferFontResponseExactly(remote, response)'), 'font buffering must run on transport responses');
assert(mgr.includes('content-encoding') && mgr.includes('content-length'), 'font wire metadata cleanup missing');
assert(mgr.includes('20260822-sj2067-r8.17'), 'R8.12 revision missing');
console.log('R8.12 regression checks passed');
